if(TARGET_PLATFORM STREQUAL "Windows Desktop")

elseif(TARGET_PLATFORM STREQUAL "Linux Desktop")

elseif(TARGET_PLATFORM STREQUAL "macOS Desktop")

  message(STATUS "Compiler: Xcode, version: " ${XCODE_VERSION})

endif()

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DTOYGINE_VERSION_MAJOR=${TOYGINE_VERSION_MAJOR} -DTOYGINE_VERSION_MINOR=${TOYGINE_VERSION_MINOR} -DTOYGINE_VERSION_MAINTENANCE=${TOYGINE_VERSION_MAINTENANCE}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DTOYGINE_VERSION_MAJOR=${TOYGINE_VERSION_MAJOR} -DTOYGINE_VERSION_MINOR=${TOYGINE_VERSION_MINOR} -DTOYGINE_VERSION_MAINTENANCE=${TOYGINE_VERSION_MAINTENANCE}")

message("CMAKE_C_FLAGS=${CMAKE_C_FLAGS}")
message("CMAKE_C_FLAGS_DEBUG=${CMAKE_C_FLAGS_DEBUG}")
message("CMAKE_C_FLAGS_RELWITHDEBINFO=${CMAKE_C_FLAGS_RELWITHDEBINFO}")
message("CMAKE_C_FLAGS_RELEASE=${CMAKE_C_FLAGS_RELEASE}")
message("CMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}")
message("CMAKE_CXX_FLAGS_DEBUG=${CMAKE_CXX_FLAGS_DEBUG}")
message("CMAKE_CXX_FLAGS_RELWITHDEBINFO=${CMAKE_CXX_FLAGS_RELWITHDEBINFO}")
message("CMAKE_CXX_FLAGS_RELEASE=${CMAKE_CXX_FLAGS_RELEASE}")

message("STATIC_LIBRARY_FLAGS=${STATIC_LIBRARY_FLAGS}")
message("STATIC_LIBRARY_FLAGS_DEBUG=${STATIC_LIBRARY_FLAGS_DEBUG}")
message("STATIC_LIBRARY_FLAGS_RELWITHDEBINFO=${STATIC_LIBRARY_FLAGS_RELWITHDEBINFO}")
message("STATIC_LIBRARY_FLAGS_RELEASE=${STATIC_LIBRARY_FLAGS_RELEASE}")

message("CMAKE_CXX_LINKER_PREFERENCE=${CMAKE_CXX_LINKER_PREFERENCE}")
message("CMAKE_CXX_LINKER_PREFERENCE_PROPAGATES=${CMAKE_CXX_LINKER_PREFERENCE_PROPAGATES}")
message("CMAKE_CXX_LINK_EXECUTABLE=${CMAKE_CXX_LINK_EXECUTABLE}")

message("LIBRARY_OUTPUT_DIRECTORY=${LIBRARY_OUTPUT_DIRECTORY}")
message("PREPROCESSOR_DEFINITIONS=${PREPROCESSOR_DEFINITIONS}")
message("CMAKE_LIBRARY_OUTPUT_DIRECTORY=${CMAKE_LIBRARY_OUTPUT_DIRECTORY}")
