cmake_minimum_required(VERSION 3.31.6 FATAL_ERROR)

if(NOT DEFINED TARGET_PLATFORM)
  if(CMAKE_SYSTEM_NAME MATCHES Windows)

    set(AVAILABLE_PLATFORMS "Windows Desktop" FORCE)

  elseif(UNIX AND NOT APPLE)

    set(AVAILABLE_PLATFORMS "Linux Desktop" FORCE)

  elseif(APPLE)

    set(AVAILABLE_PLATFORMS "macOS Desktop" FORCE)

  endif()

  list(GET AVAILABLE_PLATFORMS 0 FIRST_PLATFORM)
  set(TARGET_PLATFORM ${FIRST_PLATFORM} CACHE STRING "Select destination TARGET_PLATFORM for build" FORCE)
  set_property(CACHE TARGET_PLATFORM PROPERTY STRINGS ${AVAILABLE_PLATFORMS})
endif()
